theme: jekyll-theme-slate

title                    : "Universal-Team"
title_separator          : "|"
name                     : "Official Site"
description              : "Universal-Team's official site."
