theme       : jekyll-theme-slate
title       : "Universal-Team"
description : "Universal-Team's official site.1"
repo        : "Universal-Team/universal-team.github.io"
color       : "#00c882"

defaults:
  -
    values:
      layout: "default"
      image: "/assets/images/icons/universal-team.png"