theme: jekyll-theme-slate

title                    : "Universal-Team"
description              : "Universal-Team's official site."
repo                     : "Universal-Team/universal-team.github.io"
